name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs :
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
       

      - name: Set up Docker Componse
        uses: docker/setup-qemu-action@v2

      - name: Ensure docker compose is available
        run: docker-compose version 

      - name: Copy .env.example to .env
        run: cp ./integration-tests/.env.example ./integration-tests/.env
        
      - name: Run integration tests
        run: cd ./integration-tests && npm run test:integration
